name: state_managers_review
description: Flutter project to review diffrent statemanagers

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Network
  retrofit: ^2.2.0
  dio: ^4.0.1

  #DI
  provider: ^6.0.1

  #Architecture
  bloc: ^8.0.1
  flutter_bloc: ^8.0.1

  flutter_redux: ^0.9.0
  redux: ^5.0.0

  #Utils
  freezed: ^0.15.0+1
  freezed_annotation: ^0.15.0
  json_annotation: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1
  retrofit_generator: ^2.2.0
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true